#!/usr/bin/env bash
# Print every migration, in order, as one SQL script.
#
# This is the no-CLI path to getting the schema into a hosted Supabase project:
#
#   pnpm db:bundle > schema.sql
#
# then paste it into the dashboard's SQL editor and run it. Useful because it
# needs nothing installed, works from any machine, and you can read exactly what
# you are about to run before running it.
#
# The Supabase CLI (`supabase db push`) is the better long-term path once more
# than one person is applying migrations — it tracks which ones have run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cat <<'HEADER'
-- JobDrop schema — generated by scripts/bundle-migrations.sh, do not edit.
--
-- Safe to run once on an empty project. It is NOT idempotent: running it twice
-- will error on the first `create table`. To apply only new migrations, copy the
-- individual files from supabase/migrations/ instead.

begin;
HEADER

for file in "$REPO_ROOT"/supabase/migrations/*.sql; do
  printf '\n\n-- ============================================================\n'
  printf -- '-- %s\n' "$(basename "$file")"
  printf -- '-- ============================================================\n\n'
  cat "$file"
done

cat <<'FOOTER'

commit;
FOOTER
