const {
  AndroidConfig,
  withAndroidManifest,
  withEntitlementsPlist,
  withDangerousMod,
  withPlugins,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Wires up the two native capture surfaces (doc 1 §4).
 *
 * A config plugin rather than checked-in android/ and ios/ directories: those
 * are generated by `expo prebuild` and regenerating them would wipe hand edits.
 * Everything here is reapplied on every prebuild, so the native projects stay
 * disposable.
 *
 * What it does:
 *   Android — overlay + foreground service permissions, and an ACTION_SEND
 *             intent filter so JobDrop appears in the system share sheet.
 *   iOS     — an App Group (the only way the Share Extension and the app can
 *             see the same queue) and the extension's Info.plist activation
 *             rules.
 *
 * The extension TARGET itself has to be added to the Xcode project, which
 * plain config plugins cannot do without a project-manipulation dependency.
 * See the note in withIosShareExtensionFiles below.
 */

const APP_GROUP = 'group.app.jobdrop.client';
const EXTENSION_NAME = 'JobDropShareExtension';

// ---------------------------------------------------------------- Android --

function withAndroidPermissions(config) {
  return AndroidConfig.Permissions.withPermissions(config, [
    // The bubble. Granted on a settings screen, not a runtime dialog.
    'android.permission.SYSTEM_ALERT_WINDOW',
    // Required to keep the bubble alive while the app is not in the foreground.
    'android.permission.FOREGROUND_SERVICE',
    'android.permission.FOREGROUND_SERVICE_SPECIAL_USE',
    // The ongoing notification the foreground service is required to post.
    'android.permission.POST_NOTIFICATIONS',
  ]);
}

/**
 * Puts JobDrop in the Android share sheet. This is the capture path that always
 * works — the bubble is a bonus on top of it, not a dependency, because OEM
 * skins kill overlay services (doc 1 §13).
 */
function withAndroidShareIntent(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    const activity = app.activity?.find((a) => a.$['android:name'] === '.MainActivity');

    if (!activity) {
      throw new Error('withJobDropShare: .MainActivity not found in AndroidManifest');
    }

    activity['intent-filter'] = activity['intent-filter'] ?? [];

    const alreadyPresent = activity['intent-filter'].some((filter) =>
      filter.action?.some((a) => a.$['android:name'] === 'android.intent.action.SEND'),
    );
    if (alreadyPresent) return cfg;

    activity['intent-filter'].push({
      action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
      category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
      // text/plain covers links and pasted JDs; image/* is the screenshot path
      // that M4 will parse with OCR.
      data: [{ $: { 'android:mimeType': 'text/plain' } }, { $: { 'android:mimeType': 'image/*' } }],
    });

    return cfg;
  });
}

// -------------------------------------------------------------------- iOS --

/**
 * The App Group is what makes the Share Extension possible at all: it is the
 * only storage the extension process and the app process can both see.
 */
function withIosAppGroup(config) {
  return withEntitlementsPlist(config, (cfg) => {
    const existing = cfg.modResults['com.apple.security.application-groups'] ?? [];
    if (!existing.includes(APP_GROUP)) {
      cfg.modResults['com.apple.security.application-groups'] = [...existing, APP_GROUP];
    }
    return cfg;
  });
}

/**
 * Writes the extension's source and Info.plist into the generated ios/
 * directory so they are ready for the Xcode target.
 *
 * NOTE, and this is the honest limitation: adding a new TARGET to the Xcode
 * project needs pbxproj manipulation, which is beyond what this plugin does
 * today. The files are placed correctly and the entitlements and App Group are
 * configured; creating the target itself is currently a one-time manual step
 * (or a job for `expo-share-extension`, which does exactly this). Documented in
 * docs/05-native-capture.md.
 */
function withIosShareExtensionFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const iosRoot = cfg.modRequest.platformProjectRoot;
      const targetDir = path.join(iosRoot, EXTENSION_NAME);

      fs.mkdirSync(targetDir, { recursive: true });

      const sourceDir = path.join(projectRoot, 'plugins', 'share-extension');
      for (const file of ['ShareViewController.swift']) {
        fs.copyFileSync(path.join(sourceDir, file), path.join(targetDir, file));
      }

      // The extension needs its own copy of the shared storage and uploader,
      // because it is a separate binary and cannot link the app's module.
      const moduleDir = path.join(projectRoot, 'modules', 'jobdrop-share', 'ios');
      for (const file of ['ShareStore.swift', 'ShareUploader.swift']) {
        fs.copyFileSync(path.join(moduleDir, file), path.join(targetDir, file));
      }

      fs.writeFileSync(
        path.join(targetDir, 'Info.plist'),
        `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDisplayName</key>
  <string>JobDrop</string>
  <key>CFBundleName</key>
  <string>${EXTENSION_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>XPC!</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.share-services</string>
    <key>NSExtensionPrincipalClass</key>
    <string>$(PRODUCT_MODULE_NAME).ShareViewController</string>
    <key>NSExtensionAttributes</key>
    <dict>
      <key>NSExtensionActivationRule</key>
      <dict>
        <!-- Links and text only. Images arrive in M4 with OCR. -->
        <key>NSExtensionActivationSupportsWebURLWithMaxCount</key>
        <integer>1</integer>
        <key>NSExtensionActivationSupportsWebPageWithMaxCount</key>
        <integer>1</integer>
        <key>NSExtensionActivationSupportsText</key>
        <true/>
      </dict>
    </dict>
  </dict>
</dict>
</plist>
`,
      );

      fs.writeFileSync(
        path.join(targetDir, `${EXTENSION_NAME}.entitlements`),
        `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${APP_GROUP}</string>
  </array>
</dict>
</plist>
`,
      );

      return cfg;
    },
  ]);
}

// ------------------------------------------------------------------ plugin --

module.exports = function withJobDropShare(config) {
  return withPlugins(config, [
    withAndroidPermissions,
    withAndroidShareIntent,
    withIosAppGroup,
    withIosShareExtensionFiles,
  ]);
};

module.exports.APP_GROUP = APP_GROUP;
module.exports.EXTENSION_NAME = EXTENSION_NAME;
